### ISSUE TITLE
about crnn predict.py

### ISSUE THREAD

**Issue by dcdethan** [Rid7/Table-OCR#12]
你好，请教一下，在predict.py中的56行，读入的一张图的tensor，怎么读入多张图一个batch作为tensor去做预测呢？谢谢！

**Comment by Rid7** [comment]
> 你好，请教一下，在predict.py中的56行，读入的一张图的tensor，怎么读入多张图一个batch作为tensor去做预测呢？谢谢！

可以用torch的Dataloader类实现，类似于训练过程

**Comment by dcdethan** [comment]
多谢多谢。我根据demo改好了多batch的。
