### ISSUE TITLE
repair  table

### ISSUE THREAD

**Issue by cqray1990** [Rid7/Table-OCR#7]
![mask](https://user-images.githubusercontent.com/32585434/81060764-b6a38680-8f05-11ea-83df-e4006b937849.jpg)

the lines on the top is missing ，how can i repaired？ thank you

**Comment by Rid7** [comment]
> ![mask](https://user-images.githubusercontent.com/32585434/81060764-b6a38680-8f05-11ea-83df-e4006b937849.jpg)
> 
> the lines on the top is missing ，how can i repaired？ thank you

I think get the contour of it and add a line could be helpful.

**Comment by cqray1990** [comment]
t test an image:  i found it always more than the true  cell number!
![kkkk](https://user-images.githubusercontent.com/32585434/81155263-5836e080-8fb7-11ea-8a6d-09dfc3c9ad86.jpg)
 the true cells is 15 but using the 16
cells.append([i, cols, rows, col_point, row_point, blocks])
i don't why can you  help me ?
